version: "3.7"
services:
  reverse-proxy:
    image: nginx:1.22-alpine
    container_name: reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    restart: always
    network_mode: "bridge"
